### ISSUE TITLE
rapido swallows all errors

### ISSUE THREAD

**Issue by djay** [plomino/rapido.core#11]
This means that no transaction gets rolled back. This means the DB can be left in a real mess.

**Comment by ebrehault** [comment]
I do not even remember why I decided to use events rather than regular error raising here https://github.com/plomino/rapido.core/blob/master/rapido/core/formula.py#L26 and here https://github.com/plomino/rapido.core/blob/master/rapido/core/formula.py#L41

This is really stupid.
