### ISSUE TITLE
The docs specify `blocks`, but the code checks for `block` in the URL

### ISSUE THREAD

**Issue by jean** [plomino/rapido.core#5]
The docs specify `blocks`, but the code checks for `block` in the URL path (`rapido.core.display`).

**Comment by ebrehault** [comment]
Fixed by https://github.com/plomino/rapido.plone/commit/b990b7069de50c01efebc69738c4b76378de9a23

Note: please report doc related issues on https://github.com/plomino/rapido.plone/issues
